# Generated by Django 5.1.3 on 2026-05-13 11:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('pattern', models.CharField(choices=[('solid', 'Solid'), ('stripe', 'Stripe'), ('check', 'Check'), ('print', 'Print'), ('textured', 'Textured'), ('other', 'Other')], default='solid', max_length=16)),
                ('fabric_type', models.CharField(blank=True, max_length=40)),
                ('quantity_meters', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_per_meter', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('price_per_meter', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FabricUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('order', 'Order consumption'), ('restock', 'Restock'), ('wastage', 'Wastage'), ('sample', 'Sample'), ('adjustment', 'Manual adjustment')], max_length=16)),
                ('delta_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_usage_actions', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='inventory.fabric')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
