# Generated by Django 5.1.3 on 2026-05-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricusage',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_usage', to='orders.orderlineitem'),
        ),
        migrations.AddField(
            model_name='fabricusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_usage', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['name'], name='inventory_f_name_8f5914_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['supplier'], name='inventory_f_supplie_739885_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['is_active'], name='inventory_f_is_acti_df88ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricusage',
            index=models.Index(fields=['fabric', '-created_at'], name='inventory_f_fabric__15de76_idx'),
        ),
    ]
