# Generated by Django 5.1.3 on 2026-05-13 11:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0001_initial'),
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDailyCounter',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('next_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('order_type', models.CharField(choices=[('full', 'Full bespoke order'), ('alteration', 'Alteration only')], default='full', max_length=16)),
                ('status', models.CharField(choices=[('order_received', 'Order received'), ('requirements_noted', 'Requirements noted'), ('cutting_started', 'Cutting started'), ('stitching_in_progress', 'Stitching in progress'), ('ready_for_trial', 'Ready for trial'), ('alteration_in_progress', 'Alteration in progress'), ('ready_for_qc', 'Ready for QC'), ('qc_rejected', 'QC rejected — rework'), ('ready_for_delivery', 'Ready for delivery'), ('delivered', 'Delivered')], db_index=True, default='order_received', max_length=32)),
                ('trial_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('measurement_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='measurements.measurementset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('garment_type', models.CharField(max_length=24)),
                ('fabric_description', models.CharField(blank=True, max_length=200)),
                ('meters_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('customization_notes', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line_items', to='inventory.fabric')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.order')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(choices=[('order_received', 'Order received'), ('requirements_noted', 'Requirements noted'), ('cutting_started', 'Cutting started'), ('stitching_in_progress', 'Stitching in progress'), ('ready_for_trial', 'Ready for trial'), ('alteration_in_progress', 'Alteration in progress'), ('ready_for_qc', 'Ready for QC'), ('qc_rejected', 'QC rejected — rework'), ('ready_for_delivery', 'Ready for delivery'), ('delivered', 'Delivered')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='orders_orde_client__16ef1b_idx'),
        ),
    ]
