# Generated by Django 5.2.17 on 2026-10-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("order_received", "Order received"),
                    ("requirements_noted", "Requirements noted"),
                    ("cutting_started", "Cutting started"),
                    ("stitching_in_progress", "Stitching in progress"),
                    ("ready_for_trial", "Ready for trial"),
                    ("alteration_in_progress", "Alteration in progress"),
                    ("ready_for_qc", "Ready for QC"),
                    ("qc_rejected", "QC rejected — rework"),
                    ("ready_for_delivery", "Ready for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="order_received",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatusevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("order_received", "Order received"),
                    ("requirements_noted", "Requirements noted"),
                    ("cutting_started", "Cutting started"),
                    ("stitching_in_progress", "Stitching in progress"),
                    ("ready_for_trial", "Ready for trial"),
                    ("alteration_in_progress", "Alteration in progress"),
                    ("ready_for_qc", "Ready for QC"),
                    ("qc_rejected", "QC rejected — rework"),
                    ("ready_for_delivery", "Ready for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=32,
            ),
        ),
    ]
