# Generated by Django 5.1.3 on 2026-05-13 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=120)),
                ('mobile', models.CharField(db_index=True, max_length=24, unique=True)),
                ('alt_mobile', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('age_group', models.CharField(blank=True, choices=[('under_25', 'Under 25'), ('25_34', '25 – 34'), ('35_44', '35 – 44'), ('45_54', '45 – 54'), ('55_plus', '55+')], max_length=16)),
                ('occasion_preferences', models.JSONField(blank=True, default=list)),
                ('fabric_preferences', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='crm_client_full_na_3f948f_idx'), models.Index(fields=['mobile'], name='crm_client_mobile_4b2210_idx')],
            },
        ),
    ]
